export const UI_TEXT = {
  COMMON: {
    GPS: 'GPS',
    UTC: 'UTC',
    NOT_AVAILABLE: '--',
    PREVIOUS: 'Previous',
    NEXT: 'Next',
    TAB_ARROW: '►',
  },
  TOPBAR: {
    APP_NAME: 'VisionMastar',
    MINIMIZE: 'Minimize',
    MAXIMIZE: 'Maximize',
    CLOSE: 'Close',
    SYSTEM_CONNECTION: 'חיבור מערכות',
    RECEIVING_DATA: 'קבלת נתונים',
  },
  LEFT_PANEL: {
    TABS: ['Default', 'Docking', 'Environment', 'Route'],
    LOADING_SIDEBAR: 'Loading vessel data...',
    MANUAL_MODE_ACTIVE: 'Simulation link unavailable - manual HDG/COG input enabled',
    MANUAL: 'MANUAL',
    MANUAL_HINT: 'Use mouse wheel or type digits then press Enter',
    HDG: 'HDG',
    COG: 'COG',
    SOG: 'SOG',
    BOW_PS: 'Bow P/S',
    CCRP_PS: 'CCRP P/S',
    CCRP_FA: 'CCRP F/A',
    STERN_PS: 'Stern P/S',
    SOURCE: 'Source',
    AUTONOMOUS: 'Autonomous',
  },
  ENVIRONMENT: {
    RAIN_LEVEL: 'Rain',
    WAVE_DIRECTION: 'Wave',
    SEA_STATE: 'Sea',
  },
  RADAR_TOP_INFO: {
    MODE_NORTH_UP: 'N UP',
    MODE_HEAD_UP: 'H UP',
    HDG: 'HDG',
    STW: 'STW',
    COG: 'COG',
    SOG: 'SOG',
    GYRO: 'Gyro',
    LOG: 'Log',
  },
  RADAR_BOTTOM: {
    ENHANCE_OFF: 'Enhance Off',
    MAN: 'Man',
    AFC: 'AFC',
    TXRX_A_MASTER: 'TxRx A Master',
    TRANSMIT: 'Transmit',
    MP: 'MP',
    ROW_LABELS: ['Gain', 'Rain', 'Sea', 'Tune'],
  },
  CHART_CONTROLS: {
    SELECT_POSITION: 'Select a Position On Chart',
    MANUAL_ENTRY: 'Manual Ent',
  },
  POSITION_INFO: {
    CENTER: 'Center',
    MAX: 'Max',
    CHARTS_OFF_GYRO_ON: 'Charts Off Gyro On β',
    CPA_TCPA: 'CPA / TCPA',
    CPA: 'CPA',
    TCPA: 'TCPA',
    MAN_OVERBOARD: 'Man Overboard',
    DATETIME_STAMP: '22 Jul 2014 16:00:31 UTC',
    LEFT_ARROW_SMALL: '◄',
    RIGHT_ARROW_SMALL: '►',
  },
  RIGHT_PANEL: {
    MODE_N_UP: 'N UP',
    MODE_HEAD_UP: 'Head Up',
    TRAILS_ON: 'Trails On',
    TRAILS_OFF: 'Trails Off',
    AIS_ON: 'AIS On',
    AIS_OFF: 'AIS Off',
    CHARTS_ON: 'Charts On',
    CHARTS_OFF: 'Charts Off',
    NM: 'NM',
    ZERO_TIME_MIN_SEC: '0min 00s',
    RADAR: 'Radar',
    RADAR_PICK_TITLE: 'Radar Point Selection',
    RADAR_PICK_HINT: 'Left-click to add markers. Drag a marker to move it. Right-click a marker for options.',
    RADAR_PICK_REPLACE_STATUS: 'Replace mode: left-click on radar to place the selected marker.',
    RADAR_PICK_UNDO: 'Undo',
    RADAR_PICK_UNDO_DISABLED: 'Nothing to undo',
    RADAR_PICK_CANCEL: 'Cancel',
    RADAR_PICK_CANCEL_HINT: 'Undo all changes and close',
    RADAR_PICK_CLOSE: 'Close',
    RADAR_PICK_CLOSE_HINT: 'Close and keep current changes',
    RADAR_POINT_MENU_REPLACE: 'Replace',
    RADAR_POINT_MENU_DELETE: 'Delete',
    RADAR_PICK_ACTIVE_HINT: 'Radar point selection is active',
    GROUND_STABILISED: 'Ground Stabilised',
    R_VECTORS: 'R Vectors',
    LEFT_ARROW: '◀',
    RIGHT_ARROW: '▶',
    AIS_PRIORITY: 'AIS Priority',
    CPA: 'CPA',
    CENTRE: 'Centre',
    MAX: 'Max',
    IHELP: 'iHelp',
    PRINT: 'Print',
    MAIL_ICON: '✉',
    SYNTH_ON: 'Synth On',
    COAST: 'Coast',
    NO_ALARMS: 'No Alarms',
    MOB_TITLE: 'Man Overboard',
    SELECT_POSITION_CHART: 'Select A Position On Chart',
    MANUAL_EDIT: 'Manual Edit',
    BEARING_R: 'Bearing (R)',
    BEARING_T: 'Bearing (T)',
    RANGE_NM: 'Range (nm)',
    ELAPSED_TIME: 'Elapsed Time',
    START: 'Start',
    CURS: 'Curs',
    POSN: 'Posn',
    ROUTE: 'Route',
    TRIAL: 'Trial',
    GREEN_LAT: "40°24.496'N",
    GREEN_LON: "073°49.944'W",
    RHUMB: 'Rhumb',
    MID_TAG_R: 'R',
    SHOW_MENU: 'Show Menu',
    RINGS: 'Rings',
    DATE_ROW: '22 Jul 2014 16:00:31 UTC',
    PLACEHOLDER_HMS: 'HH:mm:ss',
    DEFAULT_HMS: '00:00:00',
    TTG_HMS: 'TTG 00:15:29 HH:MM:SS',
  },
  RIGHT_PANEL_CONTROLS: {
    EBL1_DEG: 'EBL1 (°)',
    EBL2_DEG: 'EBL2 (°)',
    VRM1_NM: 'VRM1',
    VRM2_NM: 'VRM2',
    ESTIMATED_TIME: 'Estimated Time',
  },
  EBL_VRM: {
    EBL1: 'EBL1',
    VRM1: 'VRM1',
    EBL2: 'EBL2',
    VRM2: 'VRM2',
    TRUE_FLAG: 'T',
  },
  DOCKING: {
    ROT: 'ROT',
    PORT: 'Port',
    STARBOARD: 'Starboard',
    SPEED_OVER_GROUND: 'Speed Over Ground',
    BOW_PS: 'Bow P/S',
    CCRP_PS: 'CCRP P/S',
    STEM_PS: 'Stem P/S',
    CCRP_FA: 'CCRP F/A',
    PORT_RUDDER: 'Port Rudder',
    STARBOARD_RUDDER: 'Starboard Rudder',
    BOW_THRUSTER: 'Bow Thruster',
    RELATIVE_WIND: 'Relative Wind',
    TRUE_WIND: 'True Wind',
  },
} as const;
